<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\Source;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use Illuminate\Database\Capsule\Manager as DB;
use Illuminate\Database\Query\Expression;
use Illuminate\Database\Query\JoinClause;
use Illuminate\Support\Collection;

/**
 * @var Collection<int,Source> $sources
 * @var string                 $title
 * @var Tree                   $tree
 */

// lists require a unique ID in case there are multiple lists per page
$table_id             = Registry::idFactory()->id();
?>

<?php
/**
 * Fetch a list of individuals with specified Linked to a source
 *
 * @param Tree          $tree
 * @param Source        $src
 *
 */
function families(Tree $tree, source $src)
	{
	$fquery = DB::table('link')
			-> where ('l_type', '=', 'SOUR')
			-> where ('l_file', '=', $tree -> id())
			-> where ('l_to', '=', $src -> xref())
			-> select ('l_from')
			-> get();

	foreach ($fquery as $fam){
		$a = substr(json_encode($fam),11,-2);
		$hquery = DB::table('link')
			-> where ('l_type', '=', 'HUSB')
			-> where ('l_file', '=', $tree -> id())
			-> where ('l_from', '=', $a)
			-> select ('l_to')
			-> get();		
		$husb = substr(json_encode($hquery),10,-3);
		$nhquery = DB::table('name')
			-> where ('n_file', '=', $tree -> id())
			-> where ('n_id', '=', $husb)
			-> select ('n_full')
			-> get();
		$hfullname = substr(json_encode($nhquery),12,-3);

		$wquery = DB::table('link')
			-> where ('l_type', '=', 'WIFE')
			-> where ('l_file', '=', $tree -> id())
			-> where ('l_from', '=', $a)
			-> select ('l_to')
			-> get();
		$wife = substr(json_encode($wquery),10,-3);
		$nwquery = DB::table('name')
			-> where ('n_type', '=', 'NAME')
			-> where ('n_file', '=', $tree -> id())
			-> where ('n_id', '=', $wife)
			-> select ('n_full')
			-> get();
		$wfullname = substr(json_encode($nwquery),12,-3);

		if($hfullname<>"" || $wfullname<>""){
			if($hfullname<>""){
				echo htmlentities(implode(json_decode('["' . $hfullname . '"]')));
				}
			else{
				echo I18N::translate('unkown');
				}
			echo " + ";
			if($wfullname<>""){
				echo htmlentities(implode(json_decode('["' . $wfullname . '"]')));
				}
			else{
				echo I18N::translate('unkown');
				}
			echo "; ";
			}
		}
	}
$order[] = [1,'DESC'];

?>

<?php View::push('javascript') ?>
<script>
$("#<?= e($table_id) ?> > .wt-table-source").dataTable({
	processing: true,
	retrieve: true,
	columns: [
		/* Source name  */ { type: "text" },
		/* Publish      */ { type: "text" },
		/* Families     */ { type: "text" },
	],
	sorting: <?= json_encode( [[1, 'desc']], JSON_THROW_ON_ERROR) ?>
});
</script>
<?php View::endpush() ?>


<h2 class="wt-page-title">
	<?= $title ?>
</h2>

<div id="<?= e($table_id) ?>">
<table
	class="table table-bordered table-sm wt-table-source datatables d-none"
		<?= view('lists/datatables-attributes') ?>
			data-columns="<?= e(json_encode([
			['type' => 'html'],
			null,
			null,
			], JSON_THROW_ON_ERROR)) ?>"
			data-order="<?=e(json_encode($order,JSON_THROW_ON_ERROR))?>"

	<caption class="visually-hidden">
		<?= $caption ?? I18N::translate('Sources') ?>
	</caption>

	<thead>
		<tr>
			<th class="d-none d-md-table-cell"><?= I18N::translate('Title') ?></th>
			<th class="d-none d-md-table-cell"><?= I18N::translate('Publication') ?></th>
			<th class="d-none d-md-table-cell"><?= I18N::translate('Families') ?></th>
		</tr>
	</thead>

	<tbody>
		<?php foreach ($sources as $source) : ?>
			<tr class="<?= $source->isPendingAddition() ? 'wt-new' : '' ?> <?= $source->isPendingDeletion() ? 'wt-old' : '' ?>">
				<!-- Title -->
				<td class="d-none d-md-table-cell">
					<a href="<?= e($source->url()) ?>">
						<?= $source->fullName() ?>
					</a>
				</td>

				<!-- Publisher -->
				<td class="text-center" data-sort= >
					<?= Registry::elementFactory()->make('SOUR:PUBL')->value($source->facts(['PUBL'])->isNotEmpty() ? $source->facts(['PUBL'])->first()->value() : '', $tree) ?>
				</td>

				<!-- Linked individual/family -->
				<td class="d-none d-md-table-cell">
					<?php families($tree, $source); ?>
				</td>
			</tr>
		<?php endforeach ?>
	</tbody>
</table>
</div>
